<?php

namespace Database\Seeders;

use App\Models\BiayaHotel;
use Illuminate\Database\Seeder;

class BiayaHotelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $provinsi = [
            // Aceh
            [
                'provinsi' => 'ACEH',
                'kategori' => 'kategori1',
                'tarif_a' => 4420000,
                'tarif_b' => 3526000,
                'tarif_c' => 1294000,
                'tarif_d' => 556000,
                'tarif_e' => 556000,
                'tarif_f' => 556000
            ],
            [
                'provinsi' => 'ACEH',
                'kategori' => 'kategori2',
                'tarif_a' => 3500000,
                'tarif_b' => 2000000,
                'tarif_c' => 700000,
                'tarif_d' => 300000,
                'tarif_e' => 300000,
                'tarif_f' => 300000,
            ],
            [
                'provinsi' => 'ACEH',
                'kategori' => 'kategori3',
                'tarif_a' => 2500000,
                'tarif_b' => 1000000,
                'tarif_c' => 500000,
                'tarif_d' => 0,
                'tarif_e' => 0,
                'tarif_f' => 0,
            ],
            // Sumatera Utara
            [
                'provinsi' => 'SUMATERA UTARA',
                'kategori' => 'kategori1',
                'tarif_a' => 4960000,
                'tarif_b' => 1518000,
                'tarif_c' => 1100000,
                'tarif_d' => 530000,
                'tarif_e' => 530000,
                'tarif_f' => 530000,
            ],
            [
                'provinsi' => 'SUMATERA UTARA',
                'kategori' => 'kategori2',
                'tarif_a' => 3500000,
                'tarif_b' => 1000000,
                'tarif_c' => 600000,
                'tarif_d' => 300000,
                'tarif_e' => 300000,
                'tarif_f' => 300000,
            ],
            [
                'provinsi' => 'SUMATERA UTARA',
                'kategori' => 'kategori3',
                'tarif_a' => 2500000,
                'tarif_b' => 800000,
                'tarif_c' => 400000,
                'tarif_d' => 0,
                'tarif_e' => 0,
                'tarif_f' => 0,
            ],
            // Riau
            [
                'provinsi' => 'RIAU',
                'kategori' => 'kategori1',
                'tarif_a' => 3820000,
                'tarif_b' => 3119000,
                'tarif_c' => 1650000,
                'tarif_d' => 852000,
                'tarif_e' => 852000,
                'tarif_f' => 852000,
            ],
            [
                'provinsi' => 'RIAU',
                'kategori' => 'kategori2',
                'tarif_a' => 3500000,
                'tarif_b' => 2000000,
                'tarif_c' => 700000,
                'tarif_d' => 500000,
                'tarif_e' => 500000,
                'tarif_f' => 500000,
            ],
            [
                'provinsi' => 'RIAU',
                'kategori' => 'kategori3',
                'tarif_a' => 2500000,
                'tarif_b' => 1000000,
                'tarif_c' => 500000,
                'tarif_d' => 300000,
                'tarif_e' => 300000,
                'tarif_f' => 300000,
            ],
            // Kepulauan Riau
            [
                'provinsi' => 'KEPULAUAN RIAU',
                'kategori' => 'kategori1',
                'tarif_a' => 4275000,
                'tarif_b' => 1854000,
                'tarif_c' => 1037000,
                'tarif_d' => 792000,
                'tarif_e' => 792000,
                'tarif_f' => 792000,
            ],
            [
                'provinsi' => 'KEPULAUAN RIAU',
                'kategori' => 'kategori2',
                'tarif_a' => 3500000,
                'tarif_b' => 1000000,
                'tarif_c' => 500000,
                'tarif_d' => 500000,
                'tarif_e' => 500000,
                'tarif_f' => 500000,
            ],
            [
                'provinsi' => 'KEPULAUAN RIAU',
                'kategori' => 'kategori3',
                'tarif_a' => 2500000,
                'tarif_b' => 800000,
                'tarif_c' => 300000,
                'tarif_d' => 300000,
                'tarif_e' => 300000,
                'tarif_f' => 300000,
            ],
            // Jambi
            [
                'provinsi' => 'JAMBI',
                'kategori' => 'kategori1',
                'tarif_a' => 4000000,
                'tarif_b' => 3337000,
                'tarif_c' => 1212000,
                'tarif_d' => 580000,
                'tarif_e' => 580000,
                'tarif_f' => 580000,
            ],
            [
                'provinsi' => 'JAMBI',
                'kategori' => 'kategori2',
                'tarif_a' => 3500000,
                'tarif_b' => 2000000,
                'tarif_c' => 600000,
                'tarif_d' => 300000,
                'tarif_e' => 300000,
                'tarif_f' => 0,
            ],
            [
                'provinsi' => 'JAMBI',
                'kategori' => 'kategori3',
                'tarif_a' => 2500000,
                'tarif_b' => 1000000,
                'tarif_c' => 400000,
                'tarif_d' => 0,
                'tarif_e' => 0,
                'tarif_f' => 0,
            ],
            // Sumatera Barat
            [
                'provinsi' => 'SUMATERA BARAT',
                'kategori' => 'kategori1',
                'tarif_a' => 5236000,
                'tarif_b' => 3332000,
                'tarif_c' => 1353000,
                'tarif_d' => 650000,
                'tarif_e' => 650000,
                'tarif_f' => 650000,
            ],
            [
                'provinsi' => 'SUMATERA BARAT',
                'kategori' => 'kategori2',
                'tarif_a' => 3500000,
                'tarif_b' => 2000000,
                'tarif_c' => 700000,
                'tarif_d' => 300000,
                'tarif_e' => 300000,
                'tarif_f' => 300000,
            ],
            [
                'provinsi' => 'SUMATERA BARAT',
                'kategori' => 'kategori3',
                'tarif_a' => 2500000,
                'tarif_b' => 1000000,
                'tarif_c' => 500000,
                'tarif_d' => 0,
                'tarif_e' => 0,
                'tarif_f' => 0,
            ],
            // Sumatera Selatan
            [
                'provinsi' => 'SUMATERA SELATAN',
                'kategori' => 'kategori1',
                'tarif_a' => 5850000,
                'tarif_b' => 3083000,
                'tarif_c' => 1570000,
                'tarif_d' => 861000,
                'tarif_e' => 861000,
                'tarif_f' => 861000,
            ],
            [
                'provinsi' => 'SUMATERA SELATAN',
                'kategori' => 'kategori2',
                'tarif_a' => 3500000,
                'tarif_b' => 2000000,
                'tarif_c' => 500000,
                'tarif_d' => 300000,
                'tarif_e' => 300000,
                'tarif_f' => 0,
            ],
            [
                'provinsi' => 'SUMATERA SELATAN',
                'kategori' => 'kategori3',
                'tarif_a' => 2500000,
                'tarif_b' => 1000000,
                'tarif_c' => 300000,
                'tarif_d' => 0,
                'tarif_e' => 0,
                'tarif_f' => 0,
            ],
            // Lampung
            [
                'provinsi' => 'LAMPUNG',
                'kategori' => 'kategori1',
                'tarif_a' => 4491000,
                'tarif_b' => 2067000,
                'tarif_c' => 1140000,
                'tarif_d' => 580000,
                'tarif_e' => 580000,
                'tarif_f' => 580000,
            ],
            [
                'provinsi' => 'LAMPUNG',
                'kategori' => 'kategori2',
                'tarif_a' => 3500000,
                'tarif_b' => 1000000,
                'tarif_c' => 700000,
                'tarif_d' => 300000,
                'tarif_e' => 300000,
                'tarif_f' => 300000,
            ],
            [
                'provinsi' => 'LAMPUNG',
                'kategori' => 'kategori3',
                'tarif_a' => 2500000,
                'tarif_b' => 800000,
                'tarif_c' => 500000,
                'tarif_d' => 0,
                'tarif_e' => 0,
                'tarif_f' => 0,
            ],
            // Bengkulu
            [
                'provinsi' => 'BENGKULU',
                'kategori' => 'kategori1',
                'tarif_a' => 2071000,
                'tarif_b' => 1628000,
                'tarif_c' => 1546000,
                'tarif_d' => 630000,
                'tarif_e' => 630000,
                'tarif_f' => 630000,
            ],
            [
                'provinsi' => 'BENGKULU',
                'kategori' => 'kategori2',
                'tarif_a' => 1000000,
                'tarif_b' => 800000,
                'tarif_c' => 600000,
                'tarif_d' => 300000,
                'tarif_e' => 300000,
                'tarif_f' => 0,
            ],
            [
                'provinsi' => 'BENGKULU',
                'kategori' => 'kategori3',
                'tarif_a' => 900000,
                'tarif_b' => 500000,
                'tarif_c' => 400000,
                'tarif_d' => 0,
                'tarif_e' => 0,
                'tarif_f' => 0,
            ],
            // Bangka Belitung
            [
                'provinsi' => 'BANGKA BELITUNG',
                'kategori' => 'kategori1',
                'tarif_a' => 3827000,
                'tarif_b' => 2838000,
                'tarif_c' => 1957000,
                'tarif_d' => 622000,
                'tarif_e' => 622000,
                'tarif_f' => 622000,
            ],
            [
                'provinsi' => 'BANGKA BELITUNG',
                'kategori' => 'kategori2',
                'tarif_a' => 3000000,
                'tarif_b' => 1000000,
                'tarif_c' => 700000,
                'tarif_d' => 300000,
                'tarif_e' => 300000,
                'tarif_f' => 0,
            ],
            [
                'provinsi' => 'BANGKA BELITUNG',
                'kategori' => 'kategori3',
                'tarif_a' => 2500000,
                'tarif_b' => 800000,
                'tarif_c' => 500000,
                'tarif_d' => 0,
                'tarif_e' => 0,
                'tarif_f' => 0,
            ],
            // Banten
            [
                'provinsi' => 'BANTEN',
                'kategori' => 'kategori1',
                'tarif_a' => 5725000,
                'tarif_b' => 2373000,
                'tarif_c' => 1000000,
                'tarif_d' => 718000,
                'tarif_e' => 718000,
                'tarif_f' => 718000,
            ],
            [
                'provinsi' => 'BANTEN',
                'kategori' => 'kategori2',
                'tarif_a' => 3500000,
                'tarif_b' => 1000000,
                'tarif_c' => 700000,
                'tarif_d' => 500000,
                'tarif_e' => 500000,
                'tarif_f' => 300000,
            ],
            [
                'provinsi' => 'BANTEN',
                'kategori' => 'kategori3',
                'tarif_a' => 2500000,
                'tarif_b' => 800000,
                'tarif_c' => 500000,
                'tarif_d' => 0,
                'tarif_e' => 0,
                'tarif_f' => 0,
            ],
            // Jawa Barat
            [
                'provinsi' => 'JAWA BARAT',
                'kategori' => 'kategori1',
                'tarif_a' => 5381000,
                'tarif_b' => 2755000,
                'tarif_c' => 1006000,
                'tarif_d' => 570000,
                'tarif_e' => 570000,
                'tarif_f' => 570000,
            ],
            [
                'provinsi' => 'JAWA BARAT',
                'kategori' => 'kategori2',
                'tarif_a' => 3500000,
                'tarif_b' => 1000000,
                'tarif_c' => 700000,
                'tarif_d' => 300000,
                'tarif_e' => 300000,
                'tarif_f' => 300000,
            ],
            [
                'provinsi' => 'JAWA BARAT',
                'kategori' => 'kategori3',
                'tarif_a' => 2500000,
                'tarif_b' => 800000,
                'tarif_c' => 500000,
                'tarif_d' => 0,
                'tarif_e' => 0,
                'tarif_f' => 0,
            ],
            // D.K.I Jakarta
            [
                'provinsi' => 'D.K.I JAKARTA',
                'kategori' => 'kategori1',
                'tarif_a' => 5850000,
                'tarif_b' => 1490000,
                'tarif_c' => 992000,
                'tarif_d' => 730000,
                'tarif_e' => 730000,
                'tarif_f' => 730000,
            ],
            [
                'provinsi' => 'D.K.I JAKARTA',
                'kategori' => 'kategori2',
                'tarif_a' => 4500000,
                'tarif_b' => 1200000,
                'tarif_c' => 900000,
                'tarif_d' => 600000,
                'tarif_e' => 600000,
                'tarif_f' => 600000,
            ],
            [
                'provinsi' => 'D.K.I JAKARTA',
                'kategori' => 'kategori3',
                'tarif_a' => 3000000,
                'tarif_b' => 900000,
                'tarif_c' => 750000,
                'tarif_d' => 500000,
                'tarif_e' => 500000,
                'tarif_f' => 500000,
            ],
            // Jawa Tengah
            [
                'provinsi' => 'JAWA TENGAH',
                'kategori' => 'kategori1',
                'tarif_a' => 4242000,
                'tarif_b' => 1480000,
                'tarif_c' => 954000,
                'tarif_d' => 600000,
                'tarif_e' => 600000,
                'tarif_f' => 600000,
            ],
            [
                'provinsi' => 'JAWA TENGAH',
                'kategori' => 'kategori2',
                'tarif_a' => 3500000,
                'tarif_b' => 1000000,
                'tarif_c' => 700000,
                'tarif_d' => 300000,
                'tarif_e' => 300000,
                'tarif_f' => 300000,
            ],
            [
                'provinsi' => 'JAWA TENGAH',
                'kategori' => 'kategori3',
                'tarif_a' => 2500000,
                'tarif_b' => 800000,
                'tarif_c' => 500000,
                'tarif_d' => 0,
                'tarif_e' => 0,
                'tarif_f' => 0,
            ],
            // D.I Yogyakarta
            [
                'provinsi' => 'D.I YOGYAKARTA',
                'kategori' => 'kategori1',
                'tarif_a' => 5017000,
                'tarif_b' => 2695000,
                'tarif_c' => 1384000,
                'tarif_d' => 845000,
                'tarif_e' => 845000,
                'tarif_f' => 845000,
            ],
            [
                'provinsi' => 'D.I YOGYAKARTA',
                'kategori' => 'kategori2',
                'tarif_a' => 3500000,
                'tarif_b' => 1000000,
                'tarif_c' => 700000,
                'tarif_d' => 400000,
                'tarif_e' => 400000,
                'tarif_f' => 300000,
            ],
            [
                'provinsi' => 'D.I YOGYAKARTA',
                'kategori' => 'kategori3',
                'tarif_a' => 2500000,
                'tarif_b' => 800000,
                'tarif_c' => 500000,
                'tarif_d' => 300000,
                'tarif_e' => 300000,
                'tarif_f' => 0,
            ],
            // Jawa Timur
            [
                'provinsi' => 'JAWA TIMUR',
                'kategori' => 'kategori1',
                'tarif_a' => 4400000,
                'tarif_b' => 1605000,
                'tarif_c' => 1076000,
                'tarif_d' => 664000,
                'tarif_e' => 664000,
                'tarif_f' => 664000,
            ],
            [
                'provinsi' => 'JAWA TIMUR',
                'kategori' => 'kategori2',
                'tarif_a' => 3500000,
                'tarif_b' => 1000000,
                'tarif_c' => 700000,
                'tarif_d' => 400000,
                'tarif_e' => 400000,
                'tarif_f' => 400000,
            ],
            [
                'provinsi' => 'JAWA TIMUR',
                'kategori' => 'kategori3',
                'tarif_a' => 2500000,
                'tarif_b' => 800000,
                'tarif_c' => 500000,
                'tarif_d' => 0,
                'tarif_e' => 0,
                'tarif_f' => 0,
            ],
            // Bali
            [
                'provinsi' => 'BALI',
                'kategori' => 'kategori1',
                'tarif_a' => 4890000,
                'tarif_b' => 1946000,
                'tarif_c' => 990000,
                'tarif_d' => 910000,
                'tarif_e' => 910000,
                'tarif_f' => 910000,
            ],
            [
                'provinsi' => 'BALI',
                'kategori' => 'kategori2',
                'tarif_a' => 3500000,
                'tarif_b' => 1000000,
                'tarif_c' => 800000,
                'tarif_d' => 700000,
                'tarif_e' => 700000,
                'tarif_f' => 700000,
            ],
            [
                'provinsi' => 'BALI',
                'kategori' => 'kategori3',
                'tarif_a' => 2500000,
                'tarif_b' => 800000,
                'tarif_c' => 600000,
                'tarif_d' => 500000,
                'tarif_e' => 500000,
                'tarif_f' => 500000,
            ],
            // Nusa Tenggara Barat
            [
                'provinsi' => 'NUSA TENGGARA BARAT',
                'kategori' => 'kategori1',
                'tarif_a' => 3500000,
                'tarif_b' => 2648000,
                'tarif_c' => 1418000,
                'tarif_d' => 580000,
                'tarif_e' => 580000,
                'tarif_f' => 580000,
            ],
            [
                'provinsi' => 'NUSA TENGGARA BARAT',
                'kategori' => 'kategori2',
                'tarif_a' => 3000000,
                'tarif_b' => 1000000,
                'tarif_c' => 700000,
                'tarif_d' => 300000,
                'tarif_e' => 300000,
                'tarif_f' => 300000,
            ],
            [
                'provinsi' => 'NUSA TENGGARA BARAT',
                'kategori' => 'kategori3',
                'tarif_a' => 2500000,
                'tarif_b' => 800000,
                'tarif_c' => 500000,
                'tarif_d' => 0,
                'tarif_e' => 0,
                'tarif_f' => 0,
            ],
            // Nusa Tenggara Timur
            [
                'provinsi' => 'NUSA TENGGARA TIMUR',
                'kategori' => 'kategori1',
                'tarif_a' => 3000000,
                'tarif_b' => 1493000,
                'tarif_c' => 1355000,
                'tarif_d' => 550000,
                'tarif_e' => 550000,
                'tarif_f' => 550000,
            ],
            [
                'provinsi' => 'NUSA TENGGARA TIMUR',
                'kategori' => 'kategori2',
                'tarif_a' => 2500000,
                'tarif_b' => 800000,
                'tarif_c' => 700000,
                'tarif_d' => 300000,
                'tarif_e' => 300000,
                'tarif_f' => 0,
            ],
            [
                'provinsi' => 'NUSA TENGGARA TIMUR',
                'kategori' => 'kategori3',
                'tarif_a' => 2000000,
                'tarif_b' => 600000,
                'tarif_c' => 500000,
                'tarif_d' => 0,
                'tarif_e' => 0,
                'tarif_f' => 0,
            ],
            // Kalimantan Barat
            [
                'provinsi' => 'KALIMANTAN BARAT',
                'kategori' => 'kategori1',
                'tarif_a' => 2654000,
                'tarif_b' => 1538000,
                'tarif_c' => 1125000,
                'tarif_d' => 538000,
                'tarif_e' => 538000,
                'tarif_f' => 538000,
            ],
            [
                'provinsi' => 'KALIMANTAN BARAT',
                'kategori' => 'kategori2',
                'tarif_a' => 1500000,
                'tarif_b' => 1000000,
                'tarif_c' => 800000,
                'tarif_d' => 300000,
                'tarif_e' => 300000,
                'tarif_f' => 300000,
            ],
            [
                'provinsi' => 'KALIMANTAN BARAT',
                'kategori' => 'kategori3',
                'tarif_a' => 1000000,
                'tarif_b' => 800000,
                'tarif_c' => 600000,
                'tarif_d' => 0,
                'tarif_e' => 0,
                'tarif_f' => 0,
            ],
            // Kalimantan Tengah
            [
                'provinsi' => 'KALIMANTAN TENGAH',
                'kategori' => 'kategori1',
                'tarif_a' => 4901000,
                'tarif_b' => 3391000,
                'tarif_c' => 1160000,
                'tarif_d' => 659000,
                'tarif_e' => 659000,
                'tarif_f' => 659000,
            ],
            [
                'provinsi' => 'KALIMANTAN TENGAH',
                'kategori' => 'kategori2',
                'tarif_a' => 2500000,
                'tarif_b' => 1000000,
                'tarif_c' => 600000,
                'tarif_d' => 300000,
                'tarif_e' => 300000,
                'tarif_f' => 300000,
            ],
            [
                'provinsi' => 'KALIMANTAN TENGAH',
                'kategori' => 'kategori3',
                'tarif_a' => 2000000,
                'tarif_b' => 800000,
                'tarif_c' => 400000,
                'tarif_d' => 0,
                'tarif_e' => 0,
                'tarif_f' => 0,
            ],
            // Kalimantan Selatan
            [
                'provinsi' => 'KALIMANTAN SELATAN',
                'kategori' => 'kategori1',
                'tarif_a' => 4797000,
                'tarif_b' => 3316000,
                'tarif_c' => 1500000,
                'tarif_d' => 540000,
                'tarif_e' => 540000,
                'tarif_f' => 540000,
            ],
            [
                'provinsi' => 'KALIMANTAN SELATAN',
                'kategori' => 'kategori2',
                'tarif_a' => 3500000,
                'tarif_b' => 2000000,
                'tarif_c' => 800000,
                'tarif_d' => 300000,
                'tarif_e' => 300000,
                'tarif_f' => 300000,
            ],
            [
                'provinsi' => 'KALIMANTAN SELATAN',
                'kategori' => 'kategori3',
                'tarif_a' => 2500000,
                'tarif_b' => 1000000,
                'tarif_c' => 500000,
                'tarif_d' => 0,
                'tarif_e' => 0,
                'tarif_f' => 0,
            ],
            // Kalimantan Timur
            [
                'provinsi' => 'KALIMANTAN TIMUR',
                'kategori' => 'kategori1',
                'tarif_a' => 4000000,
                'tarif_b' => 2188000,
                'tarif_c' => 1507000,
                'tarif_d' => 804000,
                'tarif_e' => 804000,
                'tarif_f' => 804000,
            ],
            [
                'provinsi' => 'KALIMANTAN TIMUR',
                'kategori' => 'kategori2',
                'tarif_a' => 3500000,
                'tarif_b' => 1000000,
                'tarif_c' => 800000,
                'tarif_d' => 300000,
                'tarif_e' => 300000,
                'tarif_f' => 300000,
            ],
            [
                'provinsi' => 'KALIMANTAN TIMUR',
                'kategori' => 'kategori3',
                'tarif_a' => 2500000,
                'tarif_b' => 800000,
                'tarif_c' => 600000,
                'tarif_d' => 0,
                'tarif_e' => 0,
                'tarif_f' => 0,
            ],
            // Kalimantan Utara
            [
                'provinsi' => 'KALIMANTAN UTARA',
                'kategori' => 'kategori1',
                'tarif_a' => 4000000,
                'tarif_b' => 2188000,
                'tarif_c' => 1507000,
                'tarif_d' => 804000,
                'tarif_e' => 804000,
                'tarif_f' => 804000,
            ],
            [
                'provinsi' => 'KALIMANTAN UTARA',
                'kategori' => 'kategori2',
                'tarif_a' => 3500000,
                'tarif_b' => 1000000,
                'tarif_c' => 800000,
                'tarif_d' => 300000,
                'tarif_e' => 300000,
                'tarif_f' => 300000,
            ],
            [
                'provinsi' => 'KALIMANTAN UTARA',
                'kategori' => 'kategori3',
                'tarif_a' => 2500000,
                'tarif_b' => 800000,
                'tarif_c' => 600000,
                'tarif_d' => 0,
                'tarif_e' => 0,
                'tarif_f' => 0,
            ],
            // Sulawesi Utara
            [
                'provinsi' => 'SULAWESI UTARA',
                'kategori' => 'kategori1',
                'tarif_a' => 4919000,
                'tarif_b' => 2290000,
                'tarif_c' => 924000,
                'tarif_d' => 782000,
                'tarif_e' => 782000,
                'tarif_f' => 782000,
            ],
            [
                'provinsi' => 'SULAWESI UTARA',
                'kategori' => 'kategori2',
                'tarif_a' => 2500000,
                'tarif_b' => 1000000,
                'tarif_c' => 600000,
                'tarif_d' => 300000,
                'tarif_e' => 300000,
                'tarif_f' => 300000,
            ],
            [
                'provinsi' => 'SULAWESI UTARA',
                'kategori' => 'kategori3',
                'tarif_a' => 2000000,
                'tarif_b' => 800000,
                'tarif_c' => 400000,
                'tarif_d' => 0,
                'tarif_e' => 0,
                'tarif_f' => 0,
            ],
            // Gorontalo
            [
                'provinsi' => 'GORONTALO',
                'kategori' => 'kategori1',
                'tarif_a' => 4168000,
                'tarif_b' => 2549000,
                'tarif_c' => 1431000,
                'tarif_d' => 764000,
                'tarif_e' => 764000,
                'tarif_f' => 764000,
            ],
            [
                'provinsi' => 'GORONTALO',
                'kategori' => 'kategori2',
                'tarif_a' => 3000000,
                'tarif_b' => 1000000,
                'tarif_c' => 800000,
                'tarif_d' => 500000,
                'tarif_e' => 500000,
                'tarif_f' => 0,
            ],
            [
                'provinsi' => 'GORONTALO',
                'kategori' => 'kategori3',
                'tarif_a' => 2000000,
                'tarif_b' => 800000,
                'tarif_c' => 600000,
                'tarif_d' => 0,
                'tarif_e' => 0,
                'tarif_f' => 0,
            ],
            // Sulawesi Barat
            [
                'provinsi' => 'SULAWESI BARAT',
                'kategori' => 'kategori1',
                'tarif_a' => 4076000,
                'tarif_b' => 2581000,
                'tarif_c' => 1075000,
                'tarif_d' => 704000,
                'tarif_e' => 704000,
                'tarif_f' => 704000,
            ],
            [
                'provinsi' => 'SULAWESI BARAT',
                'kategori' => 'kategori2',
                'tarif_a' => 3000000,
                'tarif_b' => 700000,
                'tarif_c' => 600000,
                'tarif_d' => 450000,
                'tarif_e' => 450000,
                'tarif_f' => 400000,
            ],
            [
                'provinsi' => 'SULAWESI BARAT',
                'kategori' => 'kategori3',
                'tarif_a' => 2000000,
                'tarif_b' => 500000,
                'tarif_c' => 300000,
                'tarif_d' => 200000,
                'tarif_e' => 200000,
                'tarif_f' => 0,
            ],
            // Sulawesi Selatan
            [
                'provinsi' => 'SULAWESI SELATAN',
                'kategori' => 'kategori1',
                'tarif_a' => 4820000,
                'tarif_b' => 1550000,
                'tarif_c' => 1020000,
                'tarif_d' => 732000,
                'tarif_e' => 732000,
                'tarif_f' => 732000,
            ],
            [
                'provinsi' => 'SULAWESI SELATAN',
                'kategori' => 'kategori2',
                'tarif_a' => 3500000,
                'tarif_b' => 1000000,
                'tarif_c' => 800000,
                'tarif_d' => 600000,
                'tarif_e' => 600000,
                'tarif_f' => 600000,
            ],
            [
                'provinsi' => 'SULAWESI SELATAN',
                'kategori' => 'kategori3',
                'tarif_a' => 2000000,
                'tarif_b' => 800000,
                'tarif_c' => 700000,
                'tarif_d' => 500000,
                'tarif_e' => 500000,
                'tarif_f' => 500000,
            ],
            // Sulawesi Tengah
            [
                'provinsi' => 'SULAWESI TENGAH',
                'kategori' => 'kategori1',
                'tarif_a' => 2309000,
                'tarif_b' => 2027000,
                'tarif_c' => 1567000,
                'tarif_d' => 951000,
                'tarif_e' => 951000,
                'tarif_f' => 951000,
            ],
            [
                'provinsi' => 'SULAWESI TENGAH',
                'kategori' => 'kategori2',
                'tarif_a' => 1500000,
                'tarif_b' => 1000000,
                'tarif_c' => 800000,
                'tarif_d' => 600000,
                'tarif_e' => 600000,
                'tarif_f' => 600000,
            ],
            [
                'provinsi' => 'SULAWESI TENGAH',
                'kategori' => 'kategori3',
                'tarif_a' => 1000000,
                'tarif_b' => 800000,
                'tarif_c' => 600000,
                'tarif_d' => 0,
                'tarif_e' => 0,
                'tarif_f' => 0,
            ],
            // Sulawesi Tenggara
            [
                'provinsi' => 'SULAWESI TENGGARA',
                'kategori' => 'kategori1',
                'tarif_a' => 2475000,
                'tarif_b' => 2059000,
                'tarif_c' => 1297000,
                'tarif_d' => 786000,
                'tarif_e' => 786000,
                'tarif_f' => 786000,
            ],
            [
                'provinsi' => 'SULAWESI TENGGARA',
                'kategori' => 'kategori2',
                'tarif_a' => 1500000,
                'tarif_b' => 1000000,
                'tarif_c' => 700000,
                'tarif_d' => 500000,
                'tarif_e' => 500000,
                'tarif_f' => 500000,
            ],
            [
                'provinsi' => 'SULAWESI TENGGARA',
                'kategori' => 'kategori3',
                'tarif_a' => 1000000,
                'tarif_b' => 800000,
                'tarif_c' => 400000,
                'tarif_d' => 0,
                'tarif_e' => 0,
                'tarif_f' => 0,
            ],
            // Maluku
            [
                'provinsi' => 'MALUKU',
                'kategori' => 'kategori1',
                'tarif_a' => 3457000,
                'tarif_b' => 3240000,
                'tarif_c' => 1048000,
                'tarif_d' => 667000,
                'tarif_e' => 667000,
                'tarif_f' => 667000,
            ],
            [
                'provinsi' => 'MALUKU',
                'kategori' => 'kategori2',
                'tarif_a' => 2500000,
                'tarif_b' => 800000,
                'tarif_c' => 600000,
                'tarif_d' => 400000,
                'tarif_e' => 400000,
                'tarif_f' => 400000,
            ],
            [
                'provinsi' => 'MALUKU',
                'kategori' => 'kategori3',
                'tarif_a' => 2000000,
                'tarif_b' => 600000,
                'tarif_c' => 400000,
                'tarif_d' => 0,
                'tarif_e' => 0,
                'tarif_f' => 0,
            ],
            // Maluku Utara
            [
                'provinsi' => 'MALUKU UTARA',
                'kategori' => 'kategori1',
                'tarif_a' => 3440000,
                'tarif_b' => 3175000,
                'tarif_c' => 1073000,
                'tarif_d' => 600000,
                'tarif_e' => 600000,
                'tarif_f' => 600000,
            ],
            [
                'provinsi' => 'MALUKU UTARA',
                'kategori' => 'kategori2',
                'tarif_a' => 2500000,
                'tarif_b' => 1000000,
                'tarif_c' => 500000,
                'tarif_d' => 300000,
                'tarif_e' => 300000,
                'tarif_f' => 300000,
            ],
            [
                'provinsi' => 'MALUKU UTARA',
                'kategori' => 'kategori3',
                'tarif_a' => 2000000,
                'tarif_b' => 800000,
                'tarif_c' => 300000,
                'tarif_d' => 0,
                'tarif_e' => 0,
                'tarif_f' => 0,
            ],
            // Papua
            [
                'provinsi' => 'PAPUA',
                'kategori' => 'kategori1',
                'tarif_a' => 3859000,
                'tarif_b' => 3318000,
                'tarif_c' => 2521000,
                'tarif_d' => 829000,
                'tarif_e' => 829000,
                'tarif_f' => 829000,
            ],
            [
                'provinsi' => 'PAPUA',
                'kategori' => 'kategori2',
                'tarif_a' => 2500000,
                'tarif_b' => 1000000,
                'tarif_c' => 600000,
                'tarif_d' => 300000,
                'tarif_e' => 300000,
                'tarif_f' => 300000,
            ],
            [
                'provinsi' => 'PAPUA',
                'kategori' => 'kategori3',
                'tarif_a' => 2000000,
                'tarif_b' => 800000,
                'tarif_c' => 400000,
                'tarif_d' => 0,
                'tarif_e' => 0,
                'tarif_f' => 0,
            ],
            // Papua Barat
            [
                'provinsi' => 'PAPUA BARAT',
                'kategori' => 'kategori1',
                'tarif_a' => 3872000,
                'tarif_b' => 3212000,
                'tarif_c' => 2056000,
                'tarif_d' => 718000,
                'tarif_e' => 718000,
                'tarif_f' => 718000,
            ],
            [
                'provinsi' => 'PAPUA BARAT',
                'kategori' => 'kategori2',
                'tarif_a' => 2500000,
                'tarif_b' => 1000000,
                'tarif_c' => 600000,
                'tarif_d' => 300000,
                'tarif_e' => 300000,
                'tarif_f' => 300000,
            ],
            [
                'provinsi' => 'PAPUA BARAT',
                'kategori' => 'kategori3',
                'tarif_a' => 2000000,
                'tarif_b' => 800000,
                'tarif_c' => 400000,
                'tarif_d' => 0,
                'tarif_e' => 0,
                'tarif_f' => 0,
            ],
        ];

        BiayaHotel::insert($provinsi);
    }
}
